/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAO.consultaDAO;
import DAO.pacienteDAO;
import classes.consulta;

import classes.paciente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author F2258573
 */
public class cadastro_consulta extends javax.swing.JFrame {

    /**
     * Creates new form cadastro_consulta
     */
    public cadastro_consulta(){
     initComponents();
        String[] colunas = { "Nome", "CPF"};
        DefaultTableModel tabeloModelo = new DefaultTableModel(colunas, 0);
        pacienteDAO pacienteDAO = new pacienteDAO();
        List<paciente> lista= pacienteDAO.listar();
                 for(int i = 0; i < lista.size(); i++) {
      // Extraímos os dados
      paciente paciente= lista.get(i);
  
     
    
      String[] linha = { 
         paciente.getNome(), paciente.getCpf()
      };
      tabeloModelo.addRow(linha);
        
      TabelaListaPacientes.setModel(tabeloModelo);
  
       TabelaListaPacientes.repaint(); 
    }
    }
 
    private void carregarTabela(List<paciente> lista) { 
         String[] colunas = { "Nome", "CPF" };
     DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0); 
     for (paciente paciente : lista) {
         String[] linha = { paciente.getNome(), paciente.getCpf() };
      tabelaModelo.addRow(linha); } 
     TabelaListaPacientes.setModel(tabelaModelo); 
     }

      private void buscarPacientes() { 
          String nome = TxtNome.getText(); 
          String cpf =TxtCPF.getText();
          pacienteDAO pacienteDAO = new pacienteDAO();
          List<paciente> listaPacientesSelecionados = pacienteDAO.listar(nome, cpf);
           
          carregarTabela(listaPacientesSelecionados); 
      } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtReceitaObs = new javax.swing.JTextPane();
        check_consulta_realizada = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        TxtValor = new javax.swing.JTextField();
        BtnPacientes4 = new javax.swing.JButton();
        BtnPacientes8 = new javax.swing.JButton();
        Check_Pago = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListaPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consulta");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Paciente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data da consulta:");

        TxtData.setBackground(new java.awt.Color(255, 255, 255));
        TxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDataActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Receita e observações:");

        TxtReceitaObs.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TxtReceitaObs);

        check_consulta_realizada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check_consulta_realizada.setForeground(new java.awt.Color(0, 0, 0));
        check_consulta_realizada.setText("Consulta realizada ?");
        check_consulta_realizada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                check_consulta_realizadaFocusGained(evt);
            }
        });
        check_consulta_realizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_consulta_realizadaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Valor do procedimento:");

        TxtValor.setBackground(new java.awt.Color(255, 255, 255));
        TxtValor.setForeground(new java.awt.Color(0, 0, 0));

        BtnPacientes4.setBackground(new java.awt.Color(153, 153, 0));
        BtnPacientes4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPacientes4.setForeground(new java.awt.Color(0, 0, 0));
        BtnPacientes4.setText("Salvar");
        BtnPacientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPacientes4ActionPerformed(evt);
            }
        });

        BtnPacientes8.setBackground(new java.awt.Color(153, 153, 0));
        BtnPacientes8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPacientes8.setForeground(new java.awt.Color(0, 0, 0));
        BtnPacientes8.setText("Sair");
        BtnPacientes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPacientes8ActionPerformed(evt);
            }
        });

        Check_Pago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Check_Pago.setForeground(new java.awt.Color(0, 0, 0));
        Check_Pago.setText("Procedimento pago?");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome");

        TxtNome.setBackground(new java.awt.Color(255, 255, 255));
        TxtNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtNomeCaretUpdate(evt);
            }
        });
        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cpf");

        TxtCPF.setBackground(new java.awt.Color(255, 255, 255));
        TxtCPF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtCPFCaretUpdate(evt);
            }
        });

        TabelaListaPacientes.setBackground(new java.awt.Color(255, 255, 255));
        TabelaListaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelaListaPacientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_consulta_realizada, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(BtnPacientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnPacientes8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Check_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(check_consulta_realizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPacientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPacientes8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(Check_Pago)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDataActionPerformed

    private void check_consulta_realizadaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_check_consulta_realizadaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_check_consulta_realizadaFocusGained

    private void check_consulta_realizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_consulta_realizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_consulta_realizadaActionPerformed

    private void BtnPacientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPacientes4ActionPerformed

        int selectedRow = TabelaListaPacientes.getSelectedRow();
        if (selectedRow != -1)
        {
            pacienteDAO pacienteDAO = new pacienteDAO();
            paciente pacienteSelecionado = pacienteDAO.listar().get(selectedRow);
            String data = TxtData.getText(); SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = null;
            try { date = dateFormat.parse(data);
                System.out.println("Data convertida: " + date);
            } catch (ParseException e)
            { e.printStackTrace();
            }
            if (date != null)
            { consulta consulta = new consulta(pacienteSelecionado.getNome(), date);
                consulta.setReceitaObservacoes(TxtReceitaObs.getText());
                consulta.setConsultaRealizada(check_consulta_realizada.isSelected());
                consulta.setConsultaPaga(Check_Pago.isSelected());
                consulta.setValor(TxtValor.getText());
                consultaDAO consultaDAO = new consultaDAO();
                consultaDAO.cadastrar(consulta);
                 JOptionPane.showMessageDialog(this, "cadastro realizado com sucesso.");
            dispose();
            } else
            { JOptionPane.showMessageDialog(this, "Data inválida."); }
        } else { JOptionPane.showMessageDialog(this, "Selecione um paciente.");
        }

    }//GEN-LAST:event_BtnPacientes4ActionPerformed

    private void BtnPacientes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPacientes8ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnPacientes8ActionPerformed

    private void TxtNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtNomeCaretUpdate

        String nome = TxtNome.getText();
        String cpf =TxtCPF.getText();
        pacienteDAO pacienteDAO = new pacienteDAO();
        List<paciente> listaPacientesSelecionados = pacienteDAO.listar(nome, cpf);
        carregarTabela(listaPacientesSelecionados);
    }//GEN-LAST:event_TxtNomeCaretUpdate

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void TxtCPFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtCPFCaretUpdate
        String nome = TxtNome.getText();
        String cpf =TxtCPF.getText();
        pacienteDAO pacienteDAO = new pacienteDAO();
        List<paciente> listaPacientesSelecionados = pacienteDAO.listar(nome, cpf);
        carregarTabela(listaPacientesSelecionados);
    }//GEN-LAST:event_TxtCPFCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro_consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPacientes4;
    private javax.swing.JButton BtnPacientes8;
    private javax.swing.JCheckBox Check_Pago;
    private javax.swing.JTable TabelaListaPacientes;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField TxtData;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextPane TxtReceitaObs;
    private javax.swing.JTextField TxtValor;
    private javax.swing.JCheckBox check_consulta_realizada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
